import { Language } from "./i18n";

export const trendLines = {
  traditional: "M32 126 C96 118, 146 110, 200 102 C252 95, 312 88, 372 82 C430 77, 486 72, 548 68",
  ai: "M32 144 C94 142, 146 136, 200 126 C252 114, 306 98, 372 78 C432 60, 488 42, 548 24",
};

export const landingContent = {
  en: {
    trendSignals: [
      {
        value: "+1200%",
        label: "Growth in generative-AI traffic to retail sites",
        note: "Adobe Analytics, Jul 2024 to Feb 2025",
      },
      {
        value: "80%",
        label: "Share of searches where users rely on AI results",
        note: "Bain & Company, Feb 2025",
      },
      {
        value: "15-25%",
        label: "Organic traffic exposure likely to be displaced by AI answers",
        note: "Bain & Company, Feb 2025",
      },
    ],
    faqsData: [
      {
        q: "Why does GEO need to start now?",
        a: "Because the entry point to brand discovery is shifting from search-result pages to AI answer interfaces. When buyers ask ChatGPT, Doubao, or DeepSeek directly, the model surfaces only a small set of candidate brands. The later you start building GEO, the easier it is for competitors to occupy that default AI mindshare first.",
      },
      {
        q: "How is GEO different from SEO, paid media, or PR?",
        a: "SEO answers whether search engines can find you. Paid media answers whether you are willing to keep buying traffic. PR answers whether people are talking about you. GEO answers a new question: when AI assembles the answer for the user, why would it mention your brand, on what basis, and how consistently will it keep doing so?",
      },
      {
        q: "Why do strong brands still fail to appear in AI recommendations?",
        a: "The issue is usually not product quality. It is that the brand has not been systematically represented across high-trust public sources. AI needs information it can read, validate, and cross-reference. If public information is fragmented, vague, or unsupported, the model struggles to place the brand into recommendation sets reliably.",
      },
      {
        q: "What does GiuGEO actually do?",
        a: "We do not just place a few articles. We rebuild public brand assets around how AI forms brand understanding. That includes identifying high-value question clusters, structuring the brand evidence chain, filling trusted content nodes, strengthening cross-platform references, and continuously tracking mention rate and answer phrasing across major models.",
      },
      {
        q: "Why work with GiuGEO instead of building this internally over time?",
        a: "Because GEO is not a single task. It is a system that requires ongoing calibration. Internal teams can usually produce content, but they often lack a clear view of which question scenarios matter most, which public channels influence AI understanding, and which phrasing changes model citation behavior. GiuGEO links diagnosis, strategy, content structure, and monitoring into one loop so teams waste less time on trial and error.",
      },
    ],
    industriesData: [
      {
        id: "healthcare",
        draftValue: "医疗健康",
        name: "Healthcare",
        icon: "medical_services",
        tag: "Trusted coverage gap",
        riskDesc: "When trusted public information is thin, AI struggles to identify and recommend the brand consistently.",
        queryExample: "Which digital management systems are suitable for small and mid-sized healthcare providers?",
        bias: "AI is more likely to organize recommendations from trusted public sources such as regulators, hospital systems, industry research, and professional media.",
        risk: "The real issue is not brand size. It is whether AI can access clear, citable, cross-verifiable brand information from trusted public environments.",
        strategy: "Build trusted, citable content around compliance, operational efficiency, and fit-for-scenario value so models can retrieve and reference the brand with confidence.",
        beforeGeo: "AI tends to cluster recommendations around long-established vendors with richer public information.",
        afterGeo: "Once trusted information is systematically filled in, the brand has a better chance of being recognized and included in relevant AI answers.",
      },
      {
        id: "ecommerce",
        draftValue: "电商品牌",
        name: "E-commerce",
        icon: "local_mall",
        tag: "Trusted coverage gap",
        riskDesc: "When public brand information is scattered or weak, AI often repeats only the most familiar mature brands.",
        queryExample: "Which emerging womenswear brands combine strong design with solid value this year?",
        bias: "AI tends to rely first on reviews, media coverage, ranking discussions, and brand-owned sites when forming a stable brand picture.",
        risk: "Even strong products are hard to recommend proactively when the brand lacks enough high-trust public information.",
        strategy: "Build a stronger public content asset base around decision keywords, usage scenarios, and differentiators that AI can cite with consistency.",
        beforeGeo: "AI repeatedly surfaces established brands with richer public material and broader discussion volume.",
        afterGeo: "Once trusted channels consistently express the brand’s characteristics, AI can mention and recommend it more accurately in niche demand scenarios.",
      },
      {
        id: "it_tech",
        draftValue: "IT科技",
        name: "IT & Tech",
        icon: "terminal",
        tag: "Trusted coverage gap",
        riskDesc: "If technical information is not embedded in trusted communities and documentation systems, AI is unlikely to adopt it.",
        queryExample: "What kind of cloud-native security and compliance provider should globalizing companies choose?",
        bias: "AI relies heavily on official docs, developer communities, technical blogs, and implementation cases when assembling vendor recommendations.",
        risk: "What determines recommendation is not relationship access. It is whether product capability is clearly represented inside trusted technical content that AI can read and cite.",
        strategy: "Build searchable, citable, cross-verifiable technical content around architecture, best practices, implementation scenarios, and case evidence.",
        beforeGeo: "AI tends to output large vendors whose documentation systems and community traces are already mature.",
        afterGeo: "As trusted technical content becomes more complete, the brand is more likely to enter AI-led vendor selection answers and gain stable mention share.",
      },
      {
        id: "manufacturing",
        draftValue: "智能制造",
        name: "Advanced Manufacturing",
        icon: "precision_manufacturing",
        tag: "Trusted coverage gap",
        riskDesc: "Without verifiable public materials, AI cannot interpret manufacturing capability well enough to recommend it.",
        queryExample: "Source request: which suppliers in China can provide high-precision five-axis machine tools?",
        bias: "AI is more likely to reference certifications, project cases, industry coverage, spec pages, and trade-show materials from trusted public sources.",
        risk: "If capability, delivery track record, and certifications are not expressed systematically in public, AI lacks the basis to include the supplier in sourcing answers.",
        strategy: "Turn certifications, capability boundaries, typical projects, and fit-for-industry scenarios into richer public assets with multiple points of reference.",
        beforeGeo: "AI tends to mention only mature manufacturers with richer public materials and repeated coverage.",
        afterGeo: "When manufacturing capability is fully carried by trusted public information, the brand is more likely to appear in AI-generated supplier shortlists.",
      },
      {
        id: "retail",
        draftValue: "传统零售",
        name: "Retail",
        icon: "storefront",
        tag: "Trusted coverage gap",
        riskDesc: "Offline strength does not become AI-recognizable unless it is translated into verifiable public information.",
        queryExample: "How should we choose the right traffic digitization solution for our offline supermarket chain?",
        bias: "AI tends to use public inputs such as industry reports, case studies, official sites, and authoritative media to judge vendor capability.",
        risk: "If store footprint, customer scale, and delivery experience are not converted into trusted public content, AI cannot use them as recommendation evidence.",
        strategy: "Translate offline advantage, operating methodology, and real case evidence into public assets AI can read, cite, and validate.",
        beforeGeo: "AI tends to cite retail-tech and platform brands whose digital public information is already more complete.",
        afterGeo: "When offline strengths are expressed systematically, the brand has a stronger chance to be understood and recommended in the right AI scenarios.",
      },
    ],
    geoEngineNodes: [
      { id: "questions", title: "Define the question", description: "Start from how buyers ask AI, not from writing content first.", icon: "help" },
      { id: "expression", title: "Restructure the answer", description: "Turn brand information into answer formats AI can parse, summarize, and cite.", icon: "schema" },
      { id: "evidence", title: "Strengthen evidence", description: "Connect trusted sources, industry data, and distribution into one evidence chain.", icon: "verified" },
      { id: "distribution", title: "Scale distribution", description: "Keep generation, publishing, monitoring, and calibration in the same loop.", icon: "hub" },
    ],
    geoMethodLayers: [
      { title: "Question framing", detail: "Lock the real user question before deciding what the content needs to answer." },
      { title: "Conclusion first", detail: "Surface the key judgment early so models can extract and summarize it quickly." },
      { title: "Capability breakdown", detail: "Explain product capability, boundaries, and solution path instead of relying on slogans." },
      { title: "Evidence backing", detail: "Bring industry data, third-party references, and case facts into the same asset." },
      { title: "Scenario fit", detail: "Clarify who it fits, where it works best, and how it differs from alternatives." },
    ],
    geoDeliveryPoints: [
      { value: "AI-Native", title: "Structured content generation", detail: "Generate Q&A pages, comparison pages, industry pages, and evidence pages from a mapped question set, then refine them manually for strategy and tone." },
      { value: "2000+", title: "Distribution nodes and content touchpoints", detail: "Distribute across media, communities, vertical platforms, and content networks, extending into high-trust public surfaces such as GitHub, Reddit, and YouTube with 2000+ matrix accounts and touchpoints." },
      { value: "Closed Loop", title: "Mention monitoring and calibration", detail: "Track which questions trigger mentions and which phrasings get cited, then feed those learnings back into content structure and distribution strategy." },
    ],
    teamAdvantageCards: [
      {
        step: "1",
        eyebrow: "AI Logic",
        title: "We understand how models decide to cite",
        description: "We start by identifying which information models adopt in which question types, then reverse-engineer the structure, evidence order, and public phrasing that supports citation.",
        bullets: ["High-adoption structures", "Low-adoption phrasing removed", "Content organized by model reading path"],
        accent: "violet",
        visualTitle: "Adoption path",
        visualStat: "Citation-first",
        visualPoints: ["Public corpus", "Clear structure", "Cross-verifiable"],
      },
      {
        step: "2",
        eyebrow: "Strategy",
        title: "We build systems, not isolated tactics",
        description: "GEO is not content, media, and tracking stacked together. It is an operating workflow that links question modeling, evidence architecture, distribution, and calibration.",
        bullets: ["Question map and priority", "Evidence chain and content framework", "Publishing, monitoring, and iteration in one flow"],
        accent: "amber",
        visualTitle: "Workflow loop",
        visualStat: "End-to-End",
        visualPoints: ["Question", "Expression", "Evidence", "Distribution"],
      },
      {
        step: "3",
        eyebrow: "Distribution",
        title: "We know how to amplify public visibility",
        description: "We do more than update your site. We place brand information into public platforms and content networks that AI can read, retrieve, and reference more easily.",
        bullets: ["GitHub / Reddit / YouTube", "Media, communities, vertical platforms", "2000+ matrix accounts and touchpoints"],
        accent: "cyan",
        visualTitle: "Distribution network",
        visualStat: "2000+",
        visualPoints: ["GitHub", "Reddit", "YouTube", "Media"],
      },
      {
        step: "4",
        eyebrow: "Evidence",
        title: "We know what makes information credible",
        description: "AI does not only look at how a brand describes itself. It also looks at whether public information can be verified, cross-supported, and used to justify a recommendation.",
        bullets: ["Industry data and public sources", "Third-party viewpoints and references", "Case facts and external signals"],
        accent: "emerald",
        visualTitle: "Trust signals",
        visualStat: "Verified",
        visualPoints: ["Data", "References", "Cases"],
      },
      {
        step: "5",
        eyebrow: "Operations",
        title: "This is long-term operation, not one-time placement",
        description: "What matters is not one spike in exposure. It is whether the brand keeps getting mentioned, cited, and recommended across its most important AI question scenarios.",
        bullets: ["Long-term visibility tracking", "Mention share by key question", "Recommendation stability"],
        accent: "rose",
        visualTitle: "Visibility over time",
        visualStat: "Always-On",
        visualPoints: ["Mention rate", "Citation rate", "Stability"],
      },
    ],
    static: {
      heroEyebrow: "AI-era growth team",
      heroTitlePrefix: "Is your brand invisible in",
      heroTitleHighlight: "AI visibility",
      heroTitleSuffix: "?",
      heroDescription: "When buyers ask AI for the best solution, only a small set of brands get assembled into the answer. Use GEO to secure distribution advantage before those recommendation patterns harden.",
      primaryCta: "Run My Free Audit",
      secondaryCta: "How it works",
      trendEyebrow: "Traffic shift signal",
      trendTitleTop: "Beyond search-result pages,",
      trendTitleBottom: "AI answer pages are becoming the new entry point",
      trendDescription: "Users increasingly ask products like ChatGPT, Doubao, and DeepSeek directly instead of browsing pages of links. The first brand touchpoint is moving from keyword results to generative answers.",
      indexedTrend: "Indexed Trend",
      trendChartTitle: "The main surface where brands win visibility is shifting",
      traditionalLegend: "Traditional search visibility",
      aiLegend: "AI recommendation visibility",
      trendCardTitle: "Brand discovery is being redistributed",
      trendSteps: [
        "Users click through fewer link lists one by one.",
        "Models begin returning candidate answers directly.",
        "Being mentioned starts shaping first-round brand perception.",
      ],
      rawTerminal: "LLM Terminal Runtime (native state)",
      optimizedTerminal: "LLM Terminal Runtime (optimized by GiuGEO)",
      terminalQuestion: "Which cross-border compliance providers are suitable for startups?",
      generatingRaw: "Generating Context...",
      generatingOptimized: "Retrieving Optimal Context...",
      rawList: [
        "[Competitor A] - Offers broad support for early-stage teams.",
        "[Competitor B] - Well regarded for data compliance capabilities.",
        "[Industry Leader C] - Better suited for large-scale expansion projects.",
      ],
      optimizedListFirst: "[Your Brand] - A leading cross-border compliance option with strong innovation support and excellent reputation.",
      fatalGapTitle: "Critical gap:",
      fatalGapBody: "Your brand context was trimmed out of this generation. The model did not surface your leading offer.",
      flywheelTitle: "Optimization flywheel activated:",
      flywheelBody: "The model now outputs your brand as a primary recommendation, capturing higher-intent demand earlier.",
      featureTitle: "Own the generative traffic entry point",
      featureDescriptionTop: "Traditional SEO alone is no longer enough for AI-driven discovery.",
      featureDescriptionBottom: "We help models re-understand your brand through multi-layered citation and knowledge-node placement.",
      featureCards: [
        { title: "Knowledge-node penetration", body: "Inject trusted source material that binds your brand directly to high-intent demand vocabularies, improving the chance of recommendation during model weighting." },
        { title: "Multi-source citation optimization", body: "Large models rely heavily on trusted citation traces. We build a cross-reference matrix that lifts trust and retrieval priority." },
        { title: "Live feedback monitoring", body: "Track answer phrasing, context shifts, and visibility volatility across major models, then adjust quickly to preserve share of exposure." },
      ],
      industryTitle: "Across five industries, what kind of brands does AI mention more easily?",
      industryDescription: "Different industries look different on the surface, but the underlying rule is the same: AI organizes brand recommendations from trusted public information it can read, validate, and cite.",
      industryTerminalSuffix: "Industry Insight Terminal",
      industryUserAsk: "How users ask",
      industryBias: "Common AI recommendation bias",
      industryRisk: "Core risk",
      industryIntervention: "How GiuGEO intervenes",
      industryBefore: "Before GEO",
      industryAfter: "After trusted information is filled in",
      industryCtaPrefix: "Run a free AI visibility audit for",
      productEyebrow: "Product capability",
      productTitle: "How we turn GEO into a product",
      productDescription: "From question modeling and content generation to evidence strengthening and scaled distribution, we build one operating loop.",
      productEngineLabel: "GiuGEO Engine",
      productEngineTitle: "Not content outsourcing, but a system that turns your brand into answers AI is more willing to cite",
      productEngineBody: "We do not split GEO into disconnected tasks. We combine question modeling, expression restructuring, evidence strengthening, and distribution calibration into one system.",
      methodEyebrow: "GEO-5 Framework",
      methodTitle: "Structured expression, not generic copywriting",
      methodDescription: "We break AI-citable content into explicit method layers so every asset has question fit, answer clarity, and verifiable evidence.",
      deliveryEyebrow: "Delivery Layer",
      deliveryTitle: "Generation, distribution, and calibration in one delivery chain",
      deliveryDescription: "This is not just content delivery. It combines generation, distribution, and mention monitoring into a GEO system that keeps operating.",
      operatingPrinciple: "Operating Principle",
      operatingPrincipleBody: "What we deliver is not a batch of articles, but a GEO operating mechanism that can keep generating, distributing, monitoring, and recalibrating.",
      teamEyebrow: "Core advantage",
      teamTitle: "Team advantage",
      teamDescription: "Our edge is not a single strong capability. It is the ability to combine AI logic, content, evidence, and distribution into one workflow.",
      prevCardLabel: "View previous advantage card",
      nextCardLabel: "View next advantage card",
      carouselHint: "Swipe horizontally to explore the team advantage cards",
      faqEyebrow: "FAQ",
      faqTitleTop: "What you may want",
      faqTitleBottom: "to know about GEO",
      faqDescription: "As more buyers ask AI before comparing brands, the real question is no longer whether to do GEO. It is which questions to occupy first, which trusted information gaps to close, and who can make that happen.",
      faqCta: "Start my free audit now",
      comparisonAria: "Visibility trend of traditional search versus AI recommendations",
    },
  },
  zh: {
    trendSignals: [
      {
        value: "+1200%",
        label: "生成式 AI 到零售站点流量增长",
        note: "Adobe Analytics，2024年7月到2025年2月",
      },
      {
        value: "80%",
        label: "搜索用户会在相当比例查询中依赖 AI 结果",
        note: "Bain & Company，2025年2月",
      },
      {
        value: "15-25%",
        label: "自然流量面临被 AI 结果挤压的区间",
        note: "Bain & Company，2025年2月",
      },
    ],
    faqsData: [
      {
        q: "为什么现在一定要开始做 GEO？",
        a: "因为用户获取品牌信息的入口正在从传统搜索页转向 AI 答案页。当客户直接向 ChatGPT、豆包、DeepSeek 这类产品提问时，模型会先给出少量候选品牌。越晚开始建设 GEO，品牌在 AI 里的默认认知就越容易被竞争对手占据。",
      },
      {
        q: "GEO 和传统 SEO、投流、公关有什么不同？",
        a: "SEO 解决的是“搜索引擎能不能找到你”，投流解决的是“你愿不愿意持续买流量”，公关解决的是“外界有没有讨论你”。GEO 解决的是另一个新问题：当 AI 直接替用户组织答案时，它为什么会提你、凭什么提你、会不会稳定提你。",
      },
      {
        q: "为什么很多品牌明明做得不错，AI 却不推荐？",
        a: "核心原因通常不是产品不行，而是品牌信息没有被系统沉淀在高可信公开渠道里。AI 在生成答案时需要引用和组织它能读到、能验证、能交叉印证的信息。如果公开信息零散、模糊、缺少证据链，模型就很难稳定地把品牌放进推荐结果。",
      },
      {
        q: "GiuGEO 能具体帮我们做什么？",
        a: "我们不是简单做几篇内容投放，而是围绕“AI 如何形成品牌认知”来重构公开信息资产。包括：识别高价值提问场景、梳理品牌证据链、补齐高可信内容节点、增强跨平台交叉引证，并持续监测主流模型中的提及率和表述变化。",
      },
      {
        q: "为什么要和 GiuGEO 合作，而不是内部自己慢慢做？",
        a: "因为 GEO 不是单点动作，而是一套持续校准的系统工程。企业内部往往能做内容，却很难同时判断哪些提问场景值得抢、哪些渠道对 AI 认知最关键、哪些表达会真正影响模型引用。GiuGEO 的价值在于把诊断、策略、内容结构和效果监测连成闭环，减少反复试错。",
      },
    ],
    industriesData: [
      {
        id: "healthcare",
        draftValue: "医疗健康",
        name: "医疗健康",
        icon: "medical_services",
        tag: "可信信息不足",
        riskDesc: "缺少高可信公开信息时，AI 很难稳定识别并推荐品牌",
        queryExample: "有哪些适合中小规模医疗机构的数字化管理系统？",
        bias: "AI 更容易引用来自监管、医院体系、行业研究和专业媒体中的高可信信息，再据此组织推荐答案。",
        risk: "问题不在于品牌规模大小，而在于 AI 能否从高可信平台读到足够清晰、可引用、可交叉验证的品牌信息。",
        strategy: "围绕合规、效率、适配场景等核心议题，持续补齐可被 AI 抓取和引用的高可信内容与交叉引证。",
        beforeGeo: "AI 更容易集中引用已有公开资料更完整的老牌方案和通用型厂商。",
        afterGeo: "当高可信信息被持续补齐后，品牌更有机会在相关问题中被 AI 稳定识别和纳入推荐。",
      },
      {
        id: "ecommerce",
        draftValue: "电商品牌",
        name: "电商品牌",
        icon: "local_mall",
        tag: "可信信息不足",
        riskDesc: "品牌公开信息分散或薄弱时，AI 往往只会复述更常见的成熟品牌",
        queryExample: "今年有哪些兼具设计感和性价比的小众女装品牌推荐？",
        bias: "AI 往往优先参考商品评价、媒体内容、榜单讨论和品牌官网等更容易形成一致认知的公开信息源。",
        risk: "即使产品力很强，只要品牌在高可信公开渠道上的信息不足，AI 就很难给出有根据的主动推荐。",
        strategy: "围绕用户决策词、使用场景和品牌差异点，建立更完整、更一致、可被引用的公开内容资产。",
        beforeGeo: "AI 更容易反复提到公开资料更丰富、讨论度更高的成熟品牌。",
        afterGeo: "当品牌特征在可信渠道中被持续表达后，AI 更容易在细分需求下准确提及并推荐。",
      },
      {
        id: "it_tech",
        draftValue: "IT科技",
        name: "IT科技",
        icon: "terminal",
        tag: "可信信息不足",
        riskDesc: "如果技术信息没有沉淀在高可信社区和文档体系中，AI 很难主动采用",
        queryExample: "出海企业应该选择怎样的云原生安全合规服务商？",
        bias: "AI 更依赖官方文档、开发者社区、技术博客和案例资料等高可信技术信息源来组织选型建议。",
        risk: "真正影响被推荐的，不是有没有人脉，而是产品能力是否被足够清楚地沉淀到 AI 能读取和引用的可信技术语料中。",
        strategy: "围绕核心能力、方案架构、最佳实践和案例证据，持续建设可检索、可引用、可交叉验证的技术内容。",
        beforeGeo: "AI 更容易优先输出文档体系成熟、社区痕迹更重的大厂方案。",
        afterGeo: "当可信技术内容更完整后，品牌更容易进入 AI 的技术选型答案并获得稳定提及。",
      },
      {
        id: "manufacturing",
        draftValue: "智能制造",
        name: "智能制造",
        icon: "precision_manufacturing",
        tag: "可信信息不足",
        riskDesc: "缺少可验证的公开资料时，AI 很难理解制造能力并用于推荐",
        queryExample: "寻源：国内有哪些能提供高精度五轴联动机床的供应商？",
        bias: "AI 更容易参考证书资质、案例介绍、行业报道、官网参数页和展会资料等高可信公开信息。",
        risk: "如果制造能力、交付案例和资质信息没有被系统公开表达，AI 在供应商寻源时就缺少可用依据。",
        strategy: "把资质、能力边界、典型案例和行业适配场景沉淀为更完整的公开资料，并建立多点交叉引用。",
        beforeGeo: "AI 更容易只提到公开材料更丰富、被反复报道的成熟制造商。",
        afterGeo: "当制造能力被可信信息充分承载后，品牌更容易出现在 AI 的供应商候选名单中。",
      },
      {
        id: "retail",
        draftValue: "传统零售",
        name: "传统零售",
        icon: "storefront",
        tag: "可信信息不足",
        riskDesc: "线下实力如果没有转化成可验证的公开信息，AI 就难以形成品牌认知",
        queryExample: "如何为我们的线下连锁超市选择最合适的客流数字化方案？",
        bias: "AI 更容易采用来自行业报告、案例内容、官网资料和权威媒体中的公开信息来判断服务商能力。",
        risk: "线下门店、客户规模和落地经验如果没有被转化成高可信公开内容，AI 就无法据此做出推荐。",
        strategy: "将线下优势、运营方法论和真实案例转化为 AI 可读取、可引用、可验证的公开内容资产。",
        beforeGeo: "AI 更容易先引用数字公开资料更完整的新零售和平台型品牌。",
        afterGeo: "当线下优势被系统表达出来后，品牌更有机会在相关场景中被 AI 正确理解和推荐。",
      },
    ],
    geoEngineNodes: [
      { id: "questions", title: "定义问题", description: "先定义客户会如何向 AI 提问，而不是先写内容。", icon: "help" },
      { id: "expression", title: "重构表达", description: "把品牌信息加工成 AI 更容易理解、归纳和引用的答案结构。", icon: "schema" },
      { id: "evidence", title: "放大证据", description: "把权威来源、行业数据和分发网络接入同一条证据链。", icon: "verified" },
      { id: "distribution", title: "规模化分发", description: "让生成、发布、提及监测和持续校准形成真正闭环。", icon: "hub" },
    ],
    geoMethodLayers: [
      { title: "问题定义", detail: "先锁定用户真正会问的问题，再决定内容该回答什么。" },
      { title: "结论前置", detail: "让核心判断先出现，便于模型提取和归纳。" },
      { title: "能力拆解", detail: "把产品能力、边界和解决路径讲清楚，而不是只喊口号。" },
      { title: "证据背书", detail: "把行业数据、第三方引用和案例事实纳入同一篇内容。" },
      { title: "场景适配", detail: "说明适合谁、适合什么场景，以及与其他方案的差异。" },
    ],
    geoDeliveryPoints: [
      { value: "AI-Native", title: "结构化内容生成", detail: "围绕问题地图批量生成问答页、对比页、行业页和证据页，再由人工进行策略润色。" },
      { value: "2000+", title: "分发节点与内容触点", detail: "支持覆盖媒体、社区、垂类平台与内容网络，可延展至 GitHub、Reddit、YouTube 等高权重公开平台，并结合 2000+ 矩阵号与内容触点做规模化分发。" },
      { value: "Closed Loop", title: "提及监测与持续校准", detail: "持续观察哪些问题被提及、哪些表述被引用，再反向迭代内容结构与分发策略。" },
    ],
    teamAdvantageCards: [
      {
        step: "1",
        eyebrow: "AI Logic",
        title: "懂 AI 的引用逻辑",
        description: "先判断模型在哪些问题里会优先采用什么信息，再反推内容结构、证据顺序和公开表达方式。",
        bullets: ["高采纳内容结构识别", "低采纳表述方式排除", "按模型读取路径组织内容"],
        accent: "violet",
        visualTitle: "模型采用路径",
        visualStat: "引用优先",
        visualPoints: ["公开语料", "结构清晰", "可交叉验证"],
      },
      {
        step: "2",
        eyebrow: "Strategy",
        title: "懂策略，不做碎片动作",
        description: "GEO 不是内容生产、媒体发布和效果跟踪的简单相加，而是从问题建模到分发校准的一体化工作流。",
        bullets: ["问题地图与优先级", "证据链与内容框架", "发布、监测、迭代联动"],
        accent: "amber",
        visualTitle: "工作流闭环",
        visualStat: "End-to-End",
        visualPoints: ["问题", "表达", "证据", "分发"],
      },
      {
        step: "3",
        eyebrow: "Distribution",
        title: "懂执行，能把内容放大",
        description: "不只做官网内容，而是把品牌信息分发到 AI 更容易读取、抓取和引用的公开平台与内容网络里。",
        bullets: ["GitHub / Reddit / YouTube", "媒体、社区、垂类平台", "2000+ 矩阵号与触点"],
        accent: "cyan",
        visualTitle: "分发网络",
        visualStat: "2000+",
        visualPoints: ["GitHub", "Reddit", "YouTube", "Media"],
      },
      {
        step: "4",
        eyebrow: "Evidence",
        title: "懂证据链，知道怎么做可信",
        description: "AI 不只看品牌如何表述自己，更看公开信息能否被验证、能否互相印证、能否支撑结论成立。",
        bullets: ["行业数据与公开来源", "第三方引用与观点", "案例事实与外部信号"],
        accent: "emerald",
        visualTitle: "可信信号",
        visualStat: "Verified",
        visualPoints: ["数据", "引用", "案例"],
      },
      {
        step: "5",
        eyebrow: "Operations",
        title: "不是发一次，而是长期运营",
        description: "真正重要的不是单次曝光，而是品牌能否在核心问题里持续被提及、持续被引用，并稳定进入推荐结果。",
        bullets: ["长期可见性追踪", "关键问题提及率", "推荐结果稳定性"],
        accent: "rose",
        visualTitle: "长期可见性",
        visualStat: "Always-On",
        visualPoints: ["提及率", "引用率", "稳定性"],
      },
    ],
    static: {
      heroEyebrow: "智能分发时代的专属营销团队",
      heroTitlePrefix: "您的品牌在",
      heroTitleHighlight: "AI 视野中",
      heroTitleSuffix: "隐身了吗？",
      heroDescription: "当客户向 AI 询问最佳解决方案时，只有小部分品牌会被组合输出。利用 GEO 引擎，提前锁定大模型分发红利。",
      primaryCta: "免费检测我的品牌",
      secondaryCta: "了解工作原理",
      trendEyebrow: "流量迁移信号",
      trendTitleTop: "搜索结果页之外，",
      trendTitleBottom: "模型答案页正在成为新入口",
      trendDescription: "用户越来越少翻十页链接，而是直接向 ChatGPT、豆包、DeepSeek 这类产品提问。品牌的第一触点，正在从关键词检索页迁移到生成式答案页。",
      indexedTrend: "Indexed Trend",
      trendChartTitle: "品牌获取曝光的主战场，正在发生迁移",
      traditionalLegend: "传统搜索可见性",
      aiLegend: "AI 推荐可见性",
      trendCardTitle: "用户发现品牌的入口结构，正在重新分配",
      trendSteps: [
        "用户越来越少逐条点击链接。",
        "模型开始直接给出候选答案。",
        "品牌被提及，开始决定首轮认知。",
      ],
      rawTerminal: "LLM Terminal Runtime (原生状态)",
      optimizedTerminal: "LLM Terminal Runtime (经过 GiuGEO 优化)",
      terminalQuestion: "有哪些适合初创公司的出海合规服务商？",
      generatingRaw: "Generating Context...",
      generatingOptimized: "Retrieving Optimal Context...",
      rawList: [
        "[竞争对手 A] - 提供全方位的初创支持。",
        "[竞争对手 B] - 在数据合规方面享有盛誉。",
        "[行业巨头 C] - 适合大型出海项目。",
      ],
      optimizedListFirst: "[您的品牌] - 业界领先的首选出海合规方案，提供创新支持并且广受好评。",
      fatalGapTitle: "致命缺口:",
      fatalGapBody: "在此次生成会话中，关于您的品牌上下文已被裁剪。模型并未提及您的领先方案。",
      flywheelTitle: "优化飞轮启动:",
      flywheelBody: "模型已将您的品牌作为首选推荐方案输出，大幅截流高意向客户！",
      featureTitle: "掌握生成式流量入口",
      featureDescriptionTop: "传统的 SEO 已经不足以应对 AI 驱动的查询。",
      featureDescriptionBottom: "我们通过多维度的节点植入，让模型重新认识您。",
      featureCards: [
        { title: "知识节点穿透", body: "通过高质量的权威语料植入，将品牌直接绑定至核心需求词汇池，让大模型在权重计算时优先推荐。" },
        { title: "多维引证优化", body: "大语言模型高度依赖可信引证溯源机制。我们为您建立交叉引证矩阵，提升模型信赖度与抓取顺位。" },
        { title: "实时反馈监测", body: "持续追踪各大主流模型的会话回答、语境偏移和可见度波动。及时调整策略，确保持续曝光。" },
      ],
      industryTitle: "五大行业中，AI 更容易提到什么样的品牌？",
      industryDescription: "表面上看各行业问题不同，但底层逻辑一致：AI 会优先组织自己能从高可信公开信息源中读取、验证并引用的品牌信息。",
      industryTerminalSuffix: "行业洞察终端",
      industryUserAsk: "用户会怎么问",
      industryBias: "AI 常见推荐偏向",
      industryRisk: "您的核心风险",
      industryIntervention: "GiuGEO 如何切入干预",
      industryBefore: "未做 GEO 时",
      industryAfter: "补齐可信信息后",
      industryCtaPrefix: "免费检测我在",
      productEyebrow: "产品能力",
      productTitle: "我们怎么把 GEO 做成产品",
      productDescription: "从问题建模、内容生成、证据增强到规模化分发，形成完整闭环。",
      productEngineLabel: "GiuGEO Engine",
      productEngineTitle: "不是代写内容，而是把品牌加工成 AI 更愿意引用的答案",
      productEngineBody: "我们不把 GEO 拆成零散动作，而是把问题建模、表达重构、证据增强和分发校准整合成同一个系统。",
      methodEyebrow: "GEO-5 Framework",
      methodTitle: "结构化表达，不是普通写稿",
      methodDescription: "我们把 AI 可引用的内容拆成明确的方法层，让一篇内容同时具备问题针对性、答案清晰度和证据可验证性。",
      deliveryEyebrow: "Delivery Layer",
      deliveryTitle: "生成、分发与校准，做成同一条交付链",
      deliveryDescription: "不是交付几篇内容就结束，而是把生成能力、分发能力和提及监测整合在一起，让 GEO 真正变成持续运转的系统。",
      operatingPrinciple: "Operating Principle",
      operatingPrincipleBody: "交付的不是一批稿件，而是一套可以持续生成、持续分发、持续监测和持续校准的 GEO 运行机制。",
      teamEyebrow: "核心优势",
      teamTitle: "团队优势",
      teamDescription: "我们的优势，不是单一能力强，而是能把 AI、内容、证据和分发放进同一套工作流里。",
      prevCardLabel: "查看上一张优势卡片",
      nextCardLabel: "查看下一张优势卡片",
      carouselHint: "左右滑动，查看团队核心优势",
      faqEyebrow: "常见问题解答",
      faqTitleTop: "关于 GEO，",
      faqTitleBottom: "您想了解的",
      faqDescription: "如果客户越来越多先问 AI，再去比较品牌，那么企业最需要回答的已经不是“要不要做 GEO”，而是“应该先占住哪些问题、补齐哪些可信信息，以及由谁来把这件事做成”。",
      faqCta: "现在开始我的免费检测",
      comparisonAria: "传统搜索与 AI 推荐可见性趋势图",
    },
  },
} as const satisfies Record<Language, unknown>;
